---
- name: Ensure '{{ deployment_workdir }}' exists
  ansible.builtin.file:
    path: "{{ deployment_workdir }}"
    state: directory
    mode: 0755

- name: Transfer an Api artifact to the remote server
  ansible.builtin.copy:
    src: "{{ deployment_artifact }}"
    dest: "{{ deployment_workdir }}/rest-api"
    owner: "{{ deployment_user }}"
    group: "{{ deployment_group }}"
    mode: 0755
  notify: restart_app

- name: Create systemd service
  ansible.builtin.template:
    src: systemd.service.j2
    dest: "/etc/systemd/system/{{ deployment_service }}.service"
    owner: root
    group: root
    mode: 0644
  notify: restart_app

- name: Ensure systemd service is started and enabled
  ansible.builtin.systemd:
    name: "{{ deployment_service }}"
    state: started
    enabled: true
    daemon_reload: true
